Beginner.Blog/Models/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Beginner.Blog.Core;

namespace Beginner.Blog.Models
{
    /// <summary>
    /// 分类
    /// </summary>
    public class Category : BaseEntity
    {
        private ICollection<Article> _articles;
        /// <summary>
        /// 分类名称
        /// </summary>
        public string CategoryName { get; set; }
        /// <summary>
        /// 排序值
        /// </summary>
        public int Sort { get; set; }
        /// <summary>
        /// 是否置顶
        /// </summary>
        public bool IsTop { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }
        /// <summary>
        /// 文章列表
        /// </summary>
        public virtual ICollection<Article> Articles
        {
            get { return _articles ?? (_articles = new List<Article>()); }
            protected set { _articles = value; }
        }
    }
}

Beginner.Blog/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Beginner.Blog.Core;
using Beginner.Blog.Models;
using Beginner.Blog.Core.Extension;
using Beginner.Blog.ViewModels;
using Beginner.Blog.Helper;

namespace Beginner.Blog.Controllers
{
    public class CategoryController : BaseController
    {
        private readonly IRepository<Category> _categoryRepository;
        private readonly IRepository<Article> _articleRepository;

        public CategoryController(IRepository<Category> categoryRepository, IRepository<Article> articleRepository)
        {
            _categoryRepository = categoryRepository;
            _articleRepository = articleRepository;
        }


        // GET: Category
        public ActionResult List(int pageIndex = 1, int pageSize = 15)
        {
            var setting = GetSetting();
            if (setting != null)
                pageSize = setting.ManagePageSize;

            var query = _categoryRepository.Table;

            var list = query.OrderByDescending(p => p.IsTop)
                .ThenByDescending(p => p.Sort)
                .ToPagedList(pageIndex, pageSize, true);

            return View(list);
        }

        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CategoryModel model)
        {
            if (model == null)
                throw new ArgumentNullException("model");

            if (model.CategoryName.Length > 15)
            {
                ViewBag.IsError = true;
                return View();
            }

            var entity = new Category
            {
                CategoryName = model.CategoryName,
                IsTop = model.IsTop,
                Sort = model.Sort,
                CreateTime = DateTime.Now
            };

            _categoryRepository.Insert(entity);

            return RedirectToAction("List");
        }

        public ActionResult Edit()
        {
            var id = Request["id"];
            int cId = 0;
            if (string.IsNullOrEmpty(id))
                return RedirectToAction("List");
            if (!int.TryParse(id, out cId))
                return RedirectToAction("List");
            var entity = _categoryRepository.FindById(cId);

            return View(entity);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CategoryModel model)
        {
            if (model == null)
                throw new ArgumentNullException("model");
            if (model.CategoryName.Length > 15)
            {
                ViewBag.IsError = true;
                return View();
            }

            var entity = _categoryRepository.FindById(model.Id);
            entity.CategoryName = model.CategoryName;
            entity.IsTop = model.IsTop;
            entity.Sort = model.Sort;

            _categoryRepository.Update(entity);

            return RedirectToAction("List");

        }
        [HttpPost]
        public ActionResult Delete()
        {
            var id = Request["id"];
            if (string.IsNullOrEmpty(id))
                return Json(new { success = false, message = "删除失败，请刷新页面重试！" });
            int cId;
            if (!int.TryParse(id, out cId))
                return Json(new { success = false, message = "非法参数，请刷新页面重试！" });

            var exists = _articleRepository.Table.Any(p => p.CategoryId == cId);
            if (exists)
                return Json(new { success = false, message = "该分类下存在文章，请先删除文章！" });

            _categoryRepository.Delete(p => p.Id == cId);

            return Json(new { success = true, message = "删除成功!" });
        }

        [HttpGet]
        public ActionResult CheckName()
        {
            var value = Request["name"];
            if (string.IsNullOrEmpty(value))
                return Json(new { success = false, message = "名称可用！" }, JsonRequestBehavior.AllowGet);
            var flag = false;
            var query = _categoryRepository.Table;
            var id = Request["id"];
            if (!string.IsNullOrEmpty(id))
            {
                var cId = Convert.ToInt32(id);
                if (query.Any(p => p.Id == cId && p.CategoryName == value.Trim()))
                    flag = false;
                else
                    flag = query.Any(p => p.CategoryName == value.Trim());
            }
            else
            {
                flag = query.Any(p => p.CategoryName == value.Trim());
            }
            return Json(new { success = flag, message = flag ? "分类名称已存在" : "名称可用！" }, JsonRequestBehavior.AllowGet);
        }
    }
}

Beginner.Blog/Views/Category/Create.cshtml
@{
    ViewBag.Title = "创建分类";
    Layout = "~/Views/Shared/_ManageLayoutPage.cshtml";
}

<blockquote class="layui-elem-quote blog-manage-breadcrumb">
    <span class="layui-breadcrumb">
        <a href="@Url.Action("List","Category")">分类管理</a>
        <a><cite>创建分类</cite></a>
    </span>
</blockquote>
@if (ViewBag.IsError!=null && ViewBag.IsError)
{
    <div style="background-color:#f2dede; border-color:#ebccd1; color:#a94442; padding:15px; border-radius:5px; position:relative;">
        <p><strong>错误信息：</strong>分类名称过长，请控制在15个字内！</p>
        <a href="javascript:;" style="position: absolute;right: 18px; top: 17px;"><i class="layui-icon">&#x1006;</i></a>
    </div>
}
<fieldset class="layui-elem-field layui-field-title">
    <legend>创建分类</legend>
</fieldset>

@using (Html.BeginForm("Create", "Category", FormMethod.Post, new { @class = "layui-form blog-manage-form" }))
{
    @Html.AntiForgeryToken()
    <div class="layui-form-item">
        <label class="layui-form-label">分类名称</label>
        <div class="layui-input-block">
            <input type="text" name="categoryName" lay-verify="categoryName" autocomplete="off" placeholder="请输入分类名称..." class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">排序值</label>
        <div class="layui-input-block">
            <input type="number" name="sort" lay-verify="number" value="0" min="0" autocomplete="off" class="layui-input" />
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">是否置顶</label>
        <div class="layui-input-block">
            <input type="checkbox" name="isTop" lay-skin="switch" value="true" title="是否置顶" />
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" lay-submit>立即保存</button>
            <button type="reset" class="layui-btn layui-btn-primary">重置</button>
        </div>
    </div>
}
@section scripts{
    <script>
        layui.use(['form', 'layer'], function () {
            var form = layui.form()
            , layer = layui.layer
            , $ = layui.jquery;

            //自定义验证规则
            form.verify({
                categoryName: function (value) {
                    if (value === '') {
                        return '分类名称不能为空！';
                    }
                    if (value.length > 15) {
                        return '名称太长啦，请控制在15个字内';
                    }
                    var message = '';
                    $.ajax({
                        async: false, //改为同步请求
                        url: '@Url.Action("CheckName", "Category")',
                        data: {
                            name: value
                        },
                        dataType: 'json',
                        type: 'get',
                        success: function (result) {
                            if (result.success)
                                message = result.message;
                        }
                    });
                    if (message !== '')
                        return message;
                }
            });
            var $item = $('.layui-nav > .layui-nav-item');
            $item.removeClass('layui-this').eq(2).addClass('layui-this');
        });
    </script>
}

Beginner.Blog/Views/Category/Edit.cshtml
@model Beginner.Blog.Models.Category
@{
    ViewBag.Title = "编辑分类";
    Layout = "~/Views/Shared/_ManageLayoutPage.cshtml";
}
<blockquote class="layui-elem-quote blog-manage-breadcrumb">
    <span class="layui-breadcrumb">
        <a href="@Url.Action("List","Category")">分类管理</a>
        <a><cite>编辑分类</cite></a>
    </span>
</blockquote>
@if (ViewBag.IsError != null && ViewBag.IsError)
{
    <div style="background-color:#f2dede; border-color:#ebccd1; color:#a94442; padding:15px; border-radius:5px; position:relative;">
        <p><strong>错误信息：</strong>分类名称过长，请控制在15个字内！</p>
        <a href="javascript:;" style="position: absolute;right: 18px; top: 17px;"><i class="layui-icon">&#x1006;</i></a>
    </div>
}
<fieldset class="layui-elem-field layui-field-title">
    <legend>编辑分类</legend>
</fieldset>

@using (Html.BeginForm("Edit", "Category", FormMethod.Post, new { @class = "layui-form blog-manage-form" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" name="id" value="@Model.Id" />
    <div class="layui-form-item">
        <label class="layui-form-label">分类名称</label>
        <div class="layui-input-block">
            <input type="text" name="categoryName" lay-verify="categoryName" autocomplete="off" value="@Model.CategoryName" placeholder="请输入分类名称..." class="layui-input">
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">排序值</label>
        <div class="layui-input-block">
            <input type="number" name="sort" lay-verify="number" value="@Model.Sort" min="0" autocomplete="off" class="layui-input" />
        </div>
    </div>
    <div class="layui-form-item">
        <label class="layui-form-label">是否置顶</label>
        <div class="layui-input-block">
            @{
                var isTop = Model.IsTop ? "checked" : "";
            }
            <input type="checkbox" name="isTop" lay-skin="switch" value="true" @isTop title="是否置顶" />
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button class="layui-btn" lay-submit>立即保存</button>
            <button type="reset" class="layui-btn layui-btn-primary">重置</button>
        </div>
    </div>
}
@section scripts{
    <script>
        layui.use(['form', 'layer'], function () {
            var form = layui.form()
            , layer = layui.layer
            , $ = layui.jquery;

            //自定义验证规则
            form.verify({
                categoryName: function (value) {
                    if (value === '') {
                        return '分类名称不能为空！';
                    }
                    if (value.length > 15) {
                        return '名称太长啦，请控制在15个字内';
                    }
                    var message = '';
                    $.ajax({
                        async: false, //改为同步请求
                        url: '@Url.Action("CheckName", "Category")',
                        data: {
                            name: value,
                            id:@Model.Id
                        },
                        dataType: 'json',
                        type: 'get',
                        success: function (result) {
                            if (result.success)
                                message = result.message;
                        }
                    });
                    if (message !== '')
                        return message;
                }
            });
            var $item = $('.layui-nav > .layui-nav-item');
            $item.removeClass('layui-this').eq(2).addClass('layui-this');
        });
    </script>
}

Beginner.Blog/Views/Category/List.cshtml
@model Beginner.Blog.Core.PagedList<Beginner.Blog.Models.Category>
@{
    ViewBag.Title = "分类列表";
    Layout = "~/Views/Shared/_ManageLayoutPage.cshtml";
}

<blockquote class="layui-elem-quote">
    <a href="@Url.Action("Create","Category")" class="layui-btn"><i class="layui-icon">&#xe61f;</i> 创建分类</a>

</blockquote>


<div class="blog-manage-table table-responsive">
    <table class="table table-hover table-striped table-bordered">
        <thead>
            <tr>
                <th style="text-align:center; width:50px;">ID</th>
                <th>分类名称</th>
                <th>排序值</th>
                <th>创建时间</a></th>
                <th style="text-align:center;">置顶</th>
                <th>操作</th>
            </tr>
        </thead>
        <tbody>
            @if (Model.Items != null && Model.Items.Count > 0)
            {
                foreach (var item in Model.Items)
                {
                    <tr>
                        <td style="text-align:center;">@item.Id</td>
                        <td>@item.CategoryName</td>
                        <td>@item.Sort</td>
                        <td>@item.CreateTime.ToString("yyyy-MM-dd HH:mm")</td>
                        @{
                            var topText = item.IsTop ?
                                "<i class=\"layui-icon\" style=\"color:green;\">&#xe616;</i>" :
                                "<i class=\"layui-icon\" style=\"color:red;\">&#x1007;</i>";
                        }
                        <td style="text-align:center;">@Html.Raw(topText)</td>
                        <td>
                            <a href="@Url.Action("Edit", "Category", new { id = item.Id })">编辑</a>
                            <a href="javascript:;" data-id="@item.Id" data-options="del" data-name="@item.CategoryName">删除</a>
                        </td>
                    </tr>
                                }
                            }
                            else
                            {

                                <tr>
                                    <td style="text-align:center;" colspan="6">暂无数据</td>
                                </tr>
                                    }
</tbody>
    </table>
    <div class="blog-manage-page">
        <div id="page" style="padding-left:20px;"></div>
    </div>
</div>
@section scripts{
    <script>
        layui.use(['layer'], function () {
            var layer = layui.layer
            , $ = layui.jquery;

            $('a[data-options=del]').each(function () {
                var $this = $(this);

                $this.on('click', function () {
                    var id = $this.data('id');
                    var name = $this.data('name');
                    var msg = '你真的要把  <span style="color:red;">' + name + '</span> 给删除吗？<img src="' + location.origin + '/Plugins/layui/images/face/4.gif" alt="[可怜]">'
                    var title = '萌萌的提示<img src="' + location.origin + '/Plugins/layui/images/face/7.gif" alt="[害羞]">'
                    layer.confirm(msg, { icon: 3, title: title }, function (index) {
                        var params = {
                            t: Math.random(),
                            id: id
                        };
                        $.post('@Url.Action("Delete", "Category")', params, function (result) {

                            if (result.success) {
                                layer.msg(result.message, { icon: 1 }, function (index) {
                                    location.reload();
                                });
                            }
                            else {
                                layer.msg(result.message, { icon: 2 });
                            }

                        }, 'json');
                        layer.close(index);
                    });
                });
            });
            var $item = $('.layui-nav > .layui-nav-item');
            $item.removeClass('layui-this').eq(2).addClass('layui-this');


        });

    </script>
}