Beginner.Blog/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Beginner.Blog.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public ActionResult Save()
        {
            return View();
        }
    }
}

Beginner.Blog/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using System.Configuration;

namespace Beginner.Blog.Controllers
{
    public class UploadController : Controller
    {
        //目前只支持单文件
        [HttpPost]
        public ActionResult UploadImage(HttpPostedFileBase f)
        {

            var files = Request.Files;

            if (files.Count == 0)
            {
                var json = new
                {
                    code = 1,
                    msg = "没有找到要上传的文件呢，请重新选择吧。"
                };
                return Json(json);
            }
            try
            {
                var curFile = files[0];
                //扩展文件夹 e.g. /2016/10/
                var extPath = DateTime.Now.Year.ToString() + "/" + DateTime.Now.Month.ToString() + "/";
                //获取图片文件保存的完整路径
                var fileSavePath = Server.MapPath("~/uploads/images/" + extPath);
                //路径不存在则创建
                if (!Directory.Exists(fileSavePath))
                    Directory.CreateDirectory(fileSavePath);

                //获取文件名
                var fileName = Path.GetFileName(curFile?.FileName);
                //获取文件后缀名
                var filePostfixName = fileName.Substring(fileName.LastIndexOf('.'));
                //获取新文件名
                var newFileName = DateTime.Now.ToString("yyyyMMddHHmmss") + filePostfixName;
                //合并路径
                var path = Path.Combine(fileSavePath, newFileName);
                //保存文件
                curFile.SaveAs(path);

                var resourcesSystemUrl = ConfigurationManager.AppSettings["ResourcesSystemUrl"];

                return Json(new
                {
                    code = 0,
                    msg = "咦？好像上传成功了呢。",
                    data = new
                    {
                        src = resourcesSystemUrl + "uploads/images/" + extPath + newFileName,
                        title = "这是图片的标题啊。"
                    }
                });
            }
            catch (Exception ex)
            {

                var json = new
                {
                    code = 1,
                    msg = "出错了，错误信息：" + ex.Message
                };
                return Json(json);
            }
        }

        public ActionResult WangEditor()
        {
            return View();
        }
    }
}

Beginner.Blog/Views/About/Index.cshtml
@{
    ViewBag.Title = "关于我";
    Layout = "~/Views/Shared/_ManageLayoutPage.cshtml";
}
<fieldset class="layui-elem-field layui-field-title">
    <legend>关于我</legend>
</fieldset>

@using (Html.BeginForm("Save", "About", FormMethod.Post, new { @class = "layui-form blog-manage-form" }))
{
    @Html.AntiForgeryToken()
    <input type="hidden" name="state" value="1" />    
    <div class="layui-form-item layui-form-text">
        <label class="layui-form-label">关于我</label>
        <div class="layui-input-block">
            <textarea class="layui-textarea layui-hide" required lay-verify="content" id="content" name="content"></textarea>
        </div>
    </div>
    <div class="layui-form-item">
        <div class="layui-input-block">
            <button type="submit" lay-submit="" class="layui-btn">保存</button>
        </div>
    </div>
}
@section scripts{
    <script>
        layui.use(['form', 'layedit', 'jquery'], function () {
            var form = layui.form()
            , layer = layui.layer
            , layedit = layui.layedit
            , $ = layui.jquery;

            //自定义验证规则
            form.verify({
                content: function (value) {
                    if (value === '') return '既然写文章、发博客，总得写点什么吧？';
                    if (value.length <= 30) return '你写的字数太少啦，起码也得写上30个字符吧。';
                }

            });

            //创建一个编辑器
            layedit.build('content', {
                uploadImage: {
                    url: '@Url.Action("UploadImage", "Upload")'
                },
                height:600
            });

            //监听提交
            form.on('submit(draft)', function (data) {

                //layer.alert(JSON.stringify(data.field), {
                //    title: '最终的提交信息'
                //})
                //将状态设置为2
                $('form input[name=state]').val('2');
                return true;
            });


        });
    </script>
}